# Default setup is given for MySQL with ruby1.9. If you're running Redmine
# with MySQL and ruby1.8, replace the adapter name with `mysql`.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lnufplzhmmpdsm
  password:	2wP6ckKxzi0yfxW_HtB_k-ZJQH
  host: ec2-54-83-43-49.compute-1.amazonaws.com
  port: 5432
  #database: production<%= ENV['TEST_ENV_NUMBER'] %>
  #socket: /var/run/mysqld/mysqld.sock

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lnufplzhmmpdsm
  password:	2wP6ckKxzi0yfxW_HtB_k-ZJQH
  host: ec2-54-83-43-49.compute-1.amazonaws.com
  port: 5432
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lnufplzhmmpdsm
  password:	2wP6ckKxzi0yfxW_HtB_k-ZJQH
  host: ec2-54-83-43-49.compute-1.amazonaws.com
  port: 5432

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.


# PostgreSQL configuration example
#production:
#  adapter: postgresql
#  database: redmine
#  host: localhost
#  username: postgres
#  password: "postgres"

# SQLite3 configuration example
#production:
#  adapter: sqlite3
#  database: db/redmine.sqlite3

# SQL Server configuration example
#production:
#  adapter: sqlserver
#  database: redmine
#  host: localhost
#  username: jenkins
#  password: jenkins
